# Basic test set
[[deqp]]
deqp = "/deqp-vk/external/vulkancts/modules/vulkan/deqp-vk"
caselists = ["/deqp-vk/mustpass/vk-main.txt"]
skips = ["install/freedreno-a6xx-skips.txt"]
fraction = 100
renderer_check = "Turnip Adreno .* 618"
prefix = "asan-"
timeout = 180
tests_per_group = 3500

# Force the spiller on one test so we see its memory usage.
[[deqp]]
deqp = "/deqp-vk/external/vulkancts/modules/vulkan/deqp-vk"
caselists = ["/deqp-vk/mustpass/vk-main.txt"]
skips = ["install/freedreno-a6xx-skips.txt"]
include = ["dEQP-VK.graphicsfuzz.barrier-in-loop-with-break"]
prefix = "spill-"
tests_per_group = 1
[deqp.env]
# Increase the hangcheck timer for our spilling tests which bump up against
# the .5s default.
FREEDRENO_HANGCHECK_MS = "2000"
IR3_SHADER_DEBUG = "spillall"
